blank_issues_enabled: false
contact_links:
  - name: StasiunFile Website
    url: https://stasiunfile.com
    about: Details & Docs for StasiunFile Public Projects

  - name: Security Report Email
    email: erzetindo@gmail.com
    about: For reports of SERIOUS Security Flaws ONLY
